######################################################################
# Automatically generated by qmake (3.0) fre. aug. 12 17:53:54 2016
######################################################################

include(defaults.pri)
TEMPLATE = subdirs
CONFIG += ordered
SUBDIRS = \
    src \
    app \
    tests

app.depends = src
tests.depends = src
